version: '2'
services:
  spark-master:
    image: jerdbo/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "9080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: jerdbo/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "9081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"